GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ3VpbGUiLCJpYXQiOjE3MDQzNzU1NjN9.8vQzWLhXg58UoOYFpK2EQUSI2AwgL30DIMEk_-RoqVw

###

DELETE http://localhost:3001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ3VpbGUiLCJpYXQiOjE3MDQzNTIzNTh9.25J-rGKgCR4ARZMf0Ln5wEs5NV_7m4G7wIZaSM09-Ss"
}


###
POST http://localhost:3001/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZ3VpbGUiLCJpYXQiOjE3MDQzNTIzNTh9.25J-rGKgCR4ARZMf0Ln5wEs5NV_7m4G7wIZaSM09-Ss"
}


###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "guile"
}